name: asiagolf_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5

  flutter: 
    sdk: flutter
  get_cli: ^1.8.1
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.9.0
  page_view_dot_indicator: ^2.3.0
  flutter_otp_text_field: ^1.1.1
  flutter_countdown_timer: ^4.1.0

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/

