name: asiagolf_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_cli: ^1.8.1
  flutter_svg: ^2.0.7
  page_view_dot_indicator: ^2.3.0
  flutter_otp_text_field: ^1.1.1
  flutter_countdown_timer: ^4.1.0
  connectivity_plus: ^4.0.2
  dio: 5.3.2
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0
  geolocator: ^10.1.0
  intl: ^0.18.1
  flutter_launcher_icons: 0.13.1
  flutter: 
    sdk: flutter
  json_to_model: ^3.2.4
  quiver: ^3.2.1
  flutter_native_splash: ^2.3.2
  flutter_screenutil: ^5.9.0
  flutter_map: ^6.0.1
  flutter_map_location_marker: ^8.0.2
  latlong2: ^0.9.0
  skeletonizer: ^0.8.0
  camera: ^0.10.5+5
  change_app_package_name: ^1.1.0
  fluttertoast: ^8.2.4
  logger: ^2.0.2+1
  

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/main_logo_launcher.png"
  image_path_ios: "assets/icons/main_logo_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  fullscreen: true
  color: "#ffffff"
  color_dark: "#ffffff"
  image: "assets/icons/main_logo_bg.png"
  android_12:
    color: "#ffffff"
    color_dark: "#2E398F"
    icon_background_color_dark: "#2E398F"
    image: "assets/icons/main_logo_bg.png"
    image_dark: "assets/icons/main_logo_bg.png"